default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: starter_development

test:
  <<: *default
  database: starter_test

production:
  <<: *default
  database: starter_production
  username: starter
  password: <%= ENV['starter_DATABASE_PASSWORD'] %>
